# Generated by Django 4.1 on 2024-06-30 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodologia', models.IntegerField(default=1)),
                ('didatica', models.IntegerField(default=1)),
                ('suporte_professor', models.IntegerField(default=1)),
                ('monitoria', models.IntegerField(default=1)),
                ('indice_recomendacao', models.IntegerField(default=1)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='subjects.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
