# Generated by Django 4.1 on 2024-07-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='didatica',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='indice_recomendacao',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='monitoria',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='suporte_professor',
        ),
        migrations.AddField(
            model_name='feedback',
            name='facilidade',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='material',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='provas',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='feedback',
            name='trabalho',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='metodologia',
            field=models.IntegerField(default=3),
        ),
    ]
