# Generated by Django 4.1 on 2024-06-28 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0002_person_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='semester_being_attended',
            field=models.IntegerField(default=1),
        ),
    ]
