# Generated by Django 4.1 on 2024-07-01 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persons', '0004_person_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
